name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # o modifica con il tuo branch principale
    
  workflow_run:
    workflows:
      - "Daily Sign Language Paper Scraper"
      - "Update My Publications Portfolio" # Assicurati che il nome combaci esattamente con il tuo file yaml
    types:
      - completed

# Add permissions required for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installiamo Bun al posto di Node.js
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Usiamo bun per installare le dipendenze (sarà velocissimo)
      - name: Install dependencies
        run: bun install

      # Usiamo bun per lanciare il comando di build di Nuxt
      - name: Generate static site
        run: bun run generate
      
      - name: Create .nojekyll file
        run: touch .output/public/.nojekyll
      
      - name: Check permissions
        run: |
          echo "Checking permissions..."
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is not set. Exiting."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
          publish_branch: gh-pages